### ISSUE TITLE
Do not generate time ranges in WMS requests

### ISSUE THREAD

**Issue by caspervdw** [nens/rain_report#39]
WMS time ranges are pending deprecation in Lizard. Rain_report apparently does "TIME=2021-01-01T00:00:00.000Z/2021-01-31T00:00:00.000Z" in (some) WMS requests. The effect is that the last part of the time range is discarded (so it is interpreted as "TIME=2021-01-01T00:00:00.000Z". In the future, this might result in a 400 error.

To make rain_report future-proof, this should be fixed.

Sentry warning: https://sentry.io/organizations/nens/issues/2083072913

**Comment by lexvand** [comment]
@caspervdw I ran into this issue. Currently, the rain report still works. Which backend issue will deprecate this backwards compatibility? I can't determine the priority now.

**Comment by caspervdw** [comment]
There is no open issue I am aware of. Currently there is a warning emitted to Sentry when this happens. So one way or another this should be solved. I like the API to be as strict as possible so I'd prefer the rain report to be changed (it will be a minor change, just removing the last part of the WMS range requests)

As an alternative we can just accept that this happens on in the Lizard API and silence the warning there.

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 

I moved this to the next sprint, because I feel it will continue causing inconvenience for backend.

An alternative could also be to migrate the customers to one of our other products? (lizard client, klimaatatlas, tile dashboards)
Also how long is the contract for this app still lasting?

**Comment by Derryrover** [comment]
@joeriverheijden 

Hi Joeri,

FYI:
The rain report is just like lizard-client also a angularJS application.
This means that I would prefer not to do any B & O unless needed (like this ticket).
I will then not actively keep these libraries up to date.
So I can also not really consider the 'rain report' as one of our core apps, because in practice I will do nothing to keep them up to date.

It may be worth considering moving the customers for this app to the future lizard-client or (klimaat-)atlas.
In a well setup configurable app, a rain report may be a simple configuration (instead of a full blown app).

kr Tom

**Comment by Derryrover** [comment]
merged without review:
https://github.com/nens/rain_report/pull/42
todo: deploy
https://github.com/nens/rain_report/releases/tag/v1.6.55

**Comment by Derryrover** [comment]
Deployed to production
