### ISSUE TITLE
Rain report broken - fix in configuration

### ISSUE THREAD

**Issue by lisannewapstra** [nens/rain_report#43]
**2107 0136 regenrapportage - Bernie (Apeldoorn)**

![image](https://user-images.githubusercontent.com/33685743/126324280-8877d156-0459-44c4-820a-c4b020c9a9ca.png)

Rain report does not work anymore. Linked to issue that the max. timesteps are exceeded.
This can be fixed in the configuration by changing:
Window =  3600000 ms
(now it is 1200000 ms ;  e.g. https://apeldoorn.lizard.net/api/v3/raster-aggregates/?agg=rrc&geom=POINT+(5.7817268+52.2588068)&rasters=730d6675&srs=EPSG:4326&start=2021-07-01T00:00:00.000Z&stop=2021-07-31T00:00:00.000Z&window=1200000 ) 

Please fix asap

@joeriverheijden @lexvand

**Comment by lexvand** [comment]
https://github.com/nens/rain_report/blob/master/app/components/api/api.js#L13

By changing `1200000` to `3600000` the response will have one item less, i.e. the rainfall recurrence stats for a 30 minute period. This is because it will no longer uses the 5 minute interval data, but the hourly interval instead. I would expect that this doesn't mess up the report (still fitting within templates?), but good thing to check.

@joeriverheijden Do you agree to this change?

**Comment by joeriverheijden** [comment]
@arjanverkerk @lexvand agree. 

So this issue has nothing to do with https://github.com/nens/lizard-client/issues/1171#issuecomment-884085141?

**Comment by arjanverkerk** [comment]
Setting a limit on the amount of timesteps to be requested at once exposed a rather suboptimal use of lizard in this case. So it is related, and if this one is easily fixed by querying a preaggregated source (configured via the window parameter) it is preferred above increasing the maximum timestep limit in lizard.

**Comment by joeriverheijden** [comment]
@arjanverkerk i agree.

**Comment by Derryrover** [comment]
@lexvand 

I made the change on staging:
https://nxt3.staging.lizard.net/report/rain/
https://github.com/nens/rain_report/releases/tag/v1.6.56

Is this correct?

Let me know so I can release for production. 
IMPORTANT: The current release is not fit for production, since it contains a staging config

**Comment by lisannewapstra** [comment]
Hi Tom, this is hard to test, since "last_value_timestamp": "2021-02-16T17:20:00Z". I am checking with Martijn Krol.

**Comment by lisannewapstra** [comment]
Maybe just release to production and I will check right after if it works correctly. If not, we can revert.

**Comment by Derryrover** [comment]
Todo: deploy
old version: v1.6.55
new version: v1.6.57

**Comment by Derryrover** [comment]
Done deploying.
Lisanne tested and looks good

**Comment by arjanverkerk** [comment]
As discussed with Lex and Joeri, we really need the higher resolution for statistics on the heaviest rainshowers. I will create a hotfix PR to increase raster-limit-timesteps from 4096 to 10000, which is greater then 288 * 31 and also a nice multiple of the optimizer temporal chunksize (100 timesteps) as opposed to the old NRR stores (512 timesteps). After this PR gets deployed probably some reverse modification on the rain report code is necessary as well.

**Comment by lexvand** [comment]
@Derryrover After further analysis of the issue we determined that lowering the accuracy of the report (i.e. no longer reporting peaks of 15 and 30 minutes) is not what we want after all. After the hotfix mentioned in the previous comment, could you decrease the window from 3600000 to 300000 ms in the RRC request?

**Comment by arjanverkerk** [comment]
@Derryrover said hotfix has landed, you can go ahead whenever you are ready for it.

**Comment by Derryrover** [comment]
Fix deployed to production.

@lexvand 

Hi Lex. Please test. kr Tom

**Comment by lexvand** [comment]
It works.
